### ISSUE TITLE
Instructor Feedback - Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [kdkoberle/FinancialAssets#4]
Looks like you have a really good start here!

- [x] ERD? Doesn't have to be anything fancy - using the diagram view in IntelliJ will work. You should be able to export that as an image.
- [x] Seems like you've been consistent with timelog and project plan updates. Keep that up!
- [x] It's time to start thinking about what classes you will need to create yet. Which controllers and which additional entities, for example.
- [x] You have a good number of DAOs in your project - time to refactor to the generic dao. You should leave all unit tests, just modify them to use the generic dao. Any new entities, should likewise be unit tested with regard to the hibernate/db "stuff”.
- [x] Remember to check off completed issue items using - [x], and then close the issue when all tasks are complete. That includes peer review feedback issues too.
- [x] Adding in .equals() on each entity will allow you to make unit testing of the various entities more thorough.
- [x] Remember to replace any printstacktrace statements and system.out.printlns with log4j. https://github.com/kdkoberle/FinancialAssets/blob/2b710ee83d00a2cc8899bcf18c7fee1937b1c335/src/test/java/com/financialassets/test/util/Database.java#L44-L49

**Comment by kdkoberle** [comment]
Hello, 
I have added the erd into git in the Design directory as "FinancialAssets-erd.png" and also finished removing all system.outs and stack traces.
I intend to get to all the other points hopefully before next week.
