### ISSUE TITLE
Design/Code Review 3

### ISSUE THREAD

**Issue by kiayang** [kdkoberle/FinancialAssets#7]
Category | Criteria | Rating/Comments
-- | -- | --
Project Overview |   | - The project created with the appropriate project structure and the login in function as well as the database tables were created.
  |   | - Graphs, frontend jsps and functionalities were not complete
  |   | - Looking at the Github history, it doesn't look like progress has been made for the last month or so, due to issue getting AWS and CRUD working
  | Other comments/notes | It was hard to review since Keith is still making changes and the code that he has is not currently working and he noted will not be the code is no longer relevant to the project.
JSP |   | None ready for review
Java Code quality |   | Still need to incorporate exception handling and error reporting to user.  Also need to incorporate code documentation.  Logging needs to be incorporated and need to review the System.out.println code.  AWS is not working.
Unit Tests |   | Will need to work on getting full test coverage and eliminate redundant code by using the set up and tear down methods.
Security |   | Not working and will need to be implemented on AWS
Web Service API Integration |   | Implemented the IEX trading api, API hookup is working, only  need to add error handling for when any error encountered from api.
Independent Research Topic |   | There is no independent research topic/technique implemented in the project
Deployment |   | The application has not been successfully deployed to AWS.

**Comment by pawaitemadisoncollege** [comment]
@kiayang Did you use one of the week 14 code quality tools to evaluate Keith's project? What are the recommendation from that analysis?
